Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false 

Layout/LineLength:
  Max: 240

Metrics/BlockLength:
  Max: 160

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Mac: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/IfUnlessModifier:
  Enabled: false
  
Lint/UselessAssignment:
  Enabled: false

